//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastramento.ModelData.Logic.Cadastramento
{
    using System;
    using System.Collections.Generic;
    
    public partial class analise
    {
        public int analiseid { get; set; }
        public Nullable<int> motoristaid { get; set; }
        public Nullable<int> veiculoid { get; set; }
        public Nullable<int> carroceriaid { get; set; }
        public System.DateTime datahoraanalise { get; set; }
        public Nullable<int> situacaocadastroid { get; set; }
        public string observacao { get; set; }
    
        public virtual situacaocadastro situacaocadastro { get; set; }
    }
}
