//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastramento.ModelData.Logic.Cadastramento
{
    using System;
    using System.Collections.Generic;
    
    public partial class carroceria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carroceria()
        {
            this.carroceria1 = new HashSet<carroceria>();
        }
    
        public int carroceriaid { get; set; }
        public string protocolo { get; set; }
        public string renavam { get; set; }
        public int tipocarroceriaid { get; set; }
        public string placa { get; set; }
        public string ufplaca { get; set; }
        public string chassi { get; set; }
        public string cidadelicenciamento { get; set; }
        public string marca { get; set; }
        public string categoriaantt { get; set; }
        public string corpredominante { get; set; }
        public string anofabricacao { get; set; }
        public string anomodelo { get; set; }
        public string nomeproprietariotransportadora { get; set; }
        public string cpfcnpj { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public int tipocargaid { get; set; }
        public string lotacaomaxima { get; set; }
        public string monitorado { get; set; }
        public string tipomonitoramento { get; set; }
        public string empresamonitoramento { get; set; }
        public string statuscarroceria { get; set; }
        public System.DateTime datavalidadecadastro { get; set; }
        public int situacaocadastroid { get; set; }
        public string documentourl { get; set; }
        public Nullable<int> veiculoid { get; set; }
        public Nullable<int> compartimentoid { get; set; }
        public Nullable<int> numerocompartimento { get; set; }
        public Nullable<int> usuarioidalteracao { get; set; }
        public Nullable<System.DateTime> datahoraalteracao { get; set; }
        public Nullable<int> usuarioidinclusao { get; set; }
        public System.DateTime datahorainclusao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carroceria> carroceria1 { get; set; }
        public virtual carroceria carroceria2 { get; set; }
        public virtual situacaocadastro situacaocadastro { get; set; }
        public virtual tipocarga tipocarga { get; set; }
        public virtual tipocarroceria tipocarroceria { get; set; }
        public virtual veiculo veiculo { get; set; }
    }
}
