//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastramento.ModelData.Logic.Cadastramento
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresaprojeto
    {
        public int empresaprojetoid { get; set; }
        public Nullable<int> empresaid { get; set; }
        public string numeroprocesso { get; set; }
        public string finalidade { get; set; }
        public Nullable<int> numeroempregoatual { get; set; }
        public Nullable<int> numeroempregofuturo { get; set; }
        public Nullable<decimal> faturamentoanualatual { get; set; }
        public Nullable<decimal> faturamentoanualfuturo { get; set; }
        public string horariofuncionamentomatutino { get; set; }
        public string horariofuncionamentovespertino { get; set; }
        public string horariofuncionamentonoturno { get; set; }
        public string localizacaoempreendimento { get; set; }
        public Nullable<decimal> areanecessariaconstruida { get; set; }
        public Nullable<decimal> areanecessariaterreno { get; set; }
        public Nullable<decimal> investimentoconstrucaoinstalacao { get; set; }
        public Nullable<decimal> investimentomaquinaequipamento { get; set; }
        public Nullable<decimal> investimentooutros { get; set; }
        public Nullable<decimal> investimentofixo { get; set; }
        public Nullable<decimal> capitalgiro { get; set; }
        public Nullable<decimal> investimentototal { get; set; }
        public string principalmateriaprimaorigemnacional { get; set; }
        public string principalmateriaprimaorigemimportada { get; set; }
        public string principalprodutoindustrializado { get; set; }
        public string capacidadeunidadeindustrial { get; set; }
        public Nullable<int> prazoimplantacaoiniciomes { get; set; }
        public Nullable<int> prazoimplantacaoinicioano { get; set; }
        public Nullable<int> prazoimplantacaoterminomes { get; set; }
        public Nullable<int> prazoimplantacaoterminoano { get; set; }
        public Nullable<int> iniciooperacaomes { get; set; }
        public Nullable<int> iniciooperacaoano { get; set; }
        public byte[] arquivo { get; set; }
        public Nullable<int> usuarioidinclusao { get; set; }
        public Nullable<System.DateTime> datahorainclusao { get; set; }
        public Nullable<int> usuarioidalteracao { get; set; }
        public Nullable<System.DateTime> datahoraalteracao { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
