//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastramento.ModelData.Logic.Cadastramento
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.empresaprojeto = new HashSet<empresaprojeto>();
            this.processo = new HashSet<processo>();
        }
    
        public int empresaid { get; set; }
        public string razaosocial { get; set; }
        public string cnpj { get; set; }
        public string inscricaoestadual { get; set; }
        public Nullable<System.DateTime> dataconstituicao { get; set; }
        public string cep { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string bairro { get; set; }
        public string complemento { get; set; }
        public string uf { get; set; }
        public Nullable<int> municipioid { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string objetivosocial { get; set; }
        public string ramoatividade { get; set; }
        public string principaisprodutos { get; set; }
        public string contatonome { get; set; }
        public string contatocpf { get; set; }
        public string contatorg { get; set; }
        public string contatocargo { get; set; }
        public string contatocep { get; set; }
        public string contatologradouro { get; set; }
        public string contatonumero { get; set; }
        public string contatobairro { get; set; }
        public string contatocomplemento { get; set; }
        public string contatouf { get; set; }
        public Nullable<int> contatomunicipioid { get; set; }
        public string contatotelefone { get; set; }
        public string contatoemail { get; set; }
        public string observacao { get; set; }
        public Nullable<int> usuarioidinclusao { get; set; }
        public Nullable<System.DateTime> datahorainclusao { get; set; }
        public Nullable<int> usuarioidalteracao { get; set; }
        public Nullable<System.DateTime> datahoraalteracao { get; set; }
        public Nullable<int> empresaidsistemaantigo { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual municipio municipio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresaprojeto> empresaprojeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processo> processo { get; set; }
    }
}
