//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastramento.ModelData.Logic.Cadastramento
{
    using System;
    using System.Collections.Generic;
    
    public partial class logacesso
    {
        public int logacessoid { get; set; }
        public string sistema { get; set; }
        public Nullable<int> usuarioid { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> datahoralog { get; set; }
        public string ip { get; set; }
        public string municipio { get; set; }
        public string browser { get; set; }
    }
}
