//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastramento.ModelData.Logic.Cadastramento
{
    using System;
    using System.Collections.Generic;
    
    public partial class processo
    {
        public int processoid { get; set; }
        public string numero { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> processotipoid { get; set; }
        public Nullable<int> tipoincentivoid { get; set; }
        public Nullable<int> cadeiaprodutivaid { get; set; }
        public string atividade { get; set; }
        public Nullable<int> processosituacaoid { get; set; }
        public Nullable<int> consideracaoid { get; set; }
        public string treinamento { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> consultorid { get; set; }
        public Nullable<int> empregoinicial { get; set; }
        public Nullable<int> empregofuturo { get; set; }
        public Nullable<int> empregototal { get; set; }
        public Nullable<decimal> investimentoinicial { get; set; }
        public Nullable<decimal> investimentofuturo { get; set; }
        public Nullable<decimal> investimentototal { get; set; }
        public string providencias { get; set; }
        public string justificativapendencia { get; set; }
        public string certificado { get; set; }
        public string ta { get; set; }
        public Nullable<System.DateTime> tadataassinatura { get; set; }
        public Nullable<System.DateTime> tadataentrega { get; set; }
        public Nullable<int> taprazoentregaprojeto { get; set; }
        public Nullable<System.DateTime> tadataentregaprojeto { get; set; }
        public string ta2 { get; set; }
        public Nullable<System.DateTime> ta2dataassinatura { get; set; }
        public Nullable<System.DateTime> ta2dataentrega { get; set; }
        public Nullable<int> ta2prazoentregaprojeto { get; set; }
        public Nullable<System.DateTime> ta2dataentregaprojeto { get; set; }
        public Nullable<decimal> percentual { get; set; }
        public Nullable<decimal> adicional { get; set; }
        public Nullable<int> prazoano1 { get; set; }
        public Nullable<int> prazomes1 { get; set; }
        public Nullable<int> prazodia1 { get; set; }
        public Nullable<int> prazoano2 { get; set; }
        public Nullable<int> prazomes2 { get; set; }
        public Nullable<int> prazodia2 { get; set; }
        public Nullable<int> prazoano3 { get; set; }
        public Nullable<int> prazomes3 { get; set; }
        public Nullable<int> prazodia3 { get; set; }
        public Nullable<int> prazoano4 { get; set; }
        public Nullable<int> prazomes4 { get; set; }
        public Nullable<int> prazodia4 { get; set; }
        public Nullable<int> prazoano5 { get; set; }
        public Nullable<int> prazomes5 { get; set; }
        public Nullable<int> prazodia5 { get; set; }
        public Nullable<System.DateTime> vigencia1inicio { get; set; }
        public Nullable<System.DateTime> vigencia1fim { get; set; }
        public Nullable<System.DateTime> vigencia2inicio { get; set; }
        public Nullable<System.DateTime> vigencia2fim { get; set; }
        public Nullable<System.DateTime> vigencia3inicio { get; set; }
        public Nullable<System.DateTime> vigencia3fim { get; set; }
        public Nullable<System.DateTime> vigencia4inicio { get; set; }
        public Nullable<System.DateTime> vigencia4fim { get; set; }
        public Nullable<System.DateTime> vigencia5inicio { get; set; }
        public Nullable<System.DateTime> vigencia5fim { get; set; }
        public string deliberacao1numero { get; set; }
        public Nullable<System.DateTime> deliberacao1data { get; set; }
        public string deliberacao2numero { get; set; }
        public Nullable<System.DateTime> deliberacao2data { get; set; }
        public string deliberacao3numero { get; set; }
        public Nullable<System.DateTime> deliberacao3data { get; set; }
        public string deliberacao4numero { get; set; }
        public Nullable<System.DateTime> deliberacao4data { get; set; }
        public string deliberacao5numero { get; set; }
        public Nullable<System.DateTime> deliberacao5data { get; set; }
        public string deliberacao6numero { get; set; }
        public Nullable<System.DateTime> deliberacao6data { get; set; }
        public Nullable<int> usuarioidinclusao { get; set; }
        public Nullable<System.DateTime> datahorainclusao { get; set; }
        public Nullable<int> usuarioidalteracao { get; set; }
        public Nullable<System.DateTime> datahoraalteracao { get; set; }
        public Nullable<int> processoidsistemaantigo { get; set; }
    
        public virtual cadeiaprodutiva cadeiaprodutiva { get; set; }
        public virtual consideracao consideracao { get; set; }
        public virtual consultor consultor { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual processosituacao processosituacao { get; set; }
        public virtual processotipo processotipo { get; set; }
        public virtual tipoincentivo tipoincentivo { get; set; }
    }
}
