//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastramento.ModelData.Logic.Cadastramento
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariomenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuariomenu()
        {
            this.usuariomenu1 = new HashSet<usuariomenu>();
            this.usuariomenuacao = new HashSet<usuariomenuacao>();
            this.usuariomenuperfilpermissao = new HashSet<usuariomenuperfilpermissao>();
        }
    
        public int usuariomenuid { get; set; }
        public Nullable<int> paiusuariomenuid { get; set; }
        public string texto { get; set; }
        public string url { get; set; }
        public string abrirnovajanela { get; set; }
        public Nullable<int> ordem { get; set; }
        public string tipo { get; set; }
        public string classeicone { get; set; }
        public string titulopagina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuariomenu> usuariomenu1 { get; set; }
        public virtual usuariomenu usuariomenu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuariomenuacao> usuariomenuacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuariomenuperfilpermissao> usuariomenuperfilpermissao { get; set; }
    }
}
